name: faceapidetectionweb
description: "A Flutter package for face detection and expression analysis using JavaScript interop, providing camera controls and photo capture capabilities for web applications."
publish_to: # Remove this line if you wish to publish to pub.dev
version: 1.0.0+4
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3  # untuk interop dengan JavaScript
  cupertino_icons: ^1.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

repository: https://github.com/yourusername/faceapidetectionweb

flutter:
  uses-material-design: true
